### ISSUE TITLE
Thanks again...

### ISSUE THREAD

**Issue by tied** [comsysto/kitchen-duty-plugin-for-atlassian-jira#9]
... for the great tutorial.

It was good to have it on the watch list for the last 2 years :)

I think it's one of the best tutorials that covers mostly a wide range of components you have in JIRA development and how they all play together. That's something that would be good to have from Atlassian itself. 

Everything is good explained :)

**Comment by clouless** [comment]
Thank you very much :) 

If you find any parts that are not so well explained let me know :)

Sorry for the long wait. I was a little confused by AtlasKit with React since Atlassian
was not so clear about it that this is only for Atlassian Cloud. That made me wait to see where Atlassian is heading but now it seems they will stick with AUI.

cheers :)
